/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Saber
 */
public class userSignIn extends javax.swing.JFrame {

    /**
     * Creates new form userSignIn
     */
    public userSignIn() {

        if (Start.titleComboBox.getSelectedItem().equals("Head Chef")) {
            filename = "head chef.txt";
        } else if (Start.titleComboBox.getSelectedItem().equals("Chef")) {
            filename = "chef.txt";
        } else if (Start.titleComboBox.getSelectedItem().equals("Assistant")) {
            filename = "assistant.txt";
        }
        database.setDB(filename);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        signInClientButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordLabel.setText("Password");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 50));

        usernameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernameLabel.setText("Username");
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 50));

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 140, 30));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 140, 30));

        signInClientButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signInClientButton.setText("Sign in");
        signInClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInClientButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signInClientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 130, 40));

        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed

    }//GEN-LAST:event_usernameFieldActionPerformed

    private void signInClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInClientButtonActionPerformed
        for (indexOfUser = 0; indexOfUser < database.user.size(); indexOfUser++) {
            if (usernameField.getText().equals(database.user.get(indexOfUser)) && passwordField.getText().equals(database.pass.get(indexOfUser))) {
                if (filename.equals("head chef.txt")) {
                    headChefPanel headChefPanel = new headChefPanel();
                    headChefPanel.setVisible(true);
                    this.setVisible(false);
                } else if (filename.equals("chef.txt")) {
                    chefPanel chefPanel = new chefPanel();
                    chefPanel.setVisible(true);
                    this.setVisible(false);
                } else if (filename.equals("assistant.txt")) {
                    assistantPanel assistantPanel = new assistantPanel();
                    assistantPanel.setVisible(true);
                    this.setVisible(false);
                }
                break;
            } else if (usernameField.getText().length() == 0 || passwordField.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Fill all feilds!");
            } else {
                JOptionPane.showMessageDialog(null, "Username or Password is incorrect");
            }
        }
    }//GEN-LAST:event_signInClientButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        database.clearDB();
        Start backToFirstMenu = new Start();
        backToFirstMenu.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userSignIn().setVisible(true);
            }
        });
    }

    static int indexOfUser;
    String filename = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton signInClientButton;
    public static javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

}
