
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHORT = 6;
  public static final int IDENTIFIER = 100;
  public static final int ANDEQ = 92;
  public static final int GT = 72;
  public static final int IMPLEMENTS = 38;
  public static final int CONST = 103;
  public static final int STRICTFP = 102;
  public static final int NOTEQ = 77;
  public static final int PLUSEQ = 87;
  public static final int RBRACK = 13;
  public static final int CATCH = 57;
  public static final int COMMA = 17;
  public static final int RBRACE = 19;
  public static final int THROW = 55;
  public static final int RPAREN = 22;
  public static final int LBRACK = 12;
  public static final int LT = 71;
  public static final int ANDAND = 81;
  public static final int OROR = 82;
  public static final int DOUBLE = 11;
  public static final int LBRACE = 18;
  public static final int TRANSIENT = 34;
  public static final int LPAREN = 21;
  public static final int XOREQ = 93;
  public static final int PROTECTED = 27;
  public static final int INTEGER_LITERAL = 95;
  public static final int NOT = 65;
  public static final int FINAL = 31;
  public static final int FLOAT = 10;
  public static final int GOTO = 104;
  public static final int URSHIFTEQ = 91;
  public static final int PACKAGE = 24;
  public static final int COMP = 64;
  public static final int EQ = 20;
  public static final int BOOLEAN_LITERAL = 97;
  public static final int MOD = 67;
  public static final int CLASS = 36;
  public static final int SUPER = 42;
  public static final int ABSTRACT = 30;
  public static final int NATIVE = 32;
  public static final int LONG = 8;
  public static final int PLUS = 62;
  public static final int QUESTION = 83;
  public static final int WHILE = 50;
  public static final int EXTENDS = 37;
  public static final int INTERFACE = 43;
  public static final int CHAR = 9;
  public static final int BOOLEAN = 4;
  public static final int SWITCH = 46;
  public static final int DO = 49;
  public static final int FOR = 51;
  public static final int RSHIFTEQ = 90;
  public static final int VOID = 39;
  public static final int DIV = 66;
  public static final int PUBLIC = 26;
  public static final int RETURN = 54;
  public static final int MULT = 16;
  public static final int ELSE = 45;
  public static final int TRY = 56;
  public static final int GTEQ = 74;
  public static final int BREAK = 52;
  public static final int DOT = 14;
  public static final int INT = 7;
  public static final int NULL_LITERAL = 101;
  public static final int THROWS = 40;
  public static final int STRING_LITERAL = 99;
  public static final int EQEQ = 76;
  public static final int EOF = 0;
  public static final int SEMICOLON = 15;
  public static final int THIS = 41;
  public static final int DEFAULT = 48;
  public static final int PRINT = 2;
  public static final int MULTEQ = 84;
  public static final int IMPORT = 25;
  public static final int MAIN = 3;
  public static final int MINUS = 63;
  public static final int LTEQ = 73;
  public static final int OR = 80;
  public static final int error = 1;
  public static final int URSHIFT = 70;
  public static final int SYNCHRONIZED = 33;
  public static final int DIVEQ = 85;
  public static final int LSHIFTEQ = 89;
  public static final int FINALLY = 58;
  public static final int CONTINUE = 53;
  public static final int INSTANCEOF = 75;
  public static final int IF = 44;
  public static final int MODEQ = 86;
  public static final int MINUSMINUS = 61;
  public static final int COLON = 23;
  public static final int CHARACTER_LITERAL = 98;
  public static final int OREQ = 94;
  public static final int VOLATILE = 35;
  public static final int CASE = 47;
  public static final int PLUSPLUS = 60;
  public static final int NEW = 59;
  public static final int RSHIFT = 69;
  public static final int BYTE = 5;
  public static final int AND = 78;
  public static final int PRIVATE = 28;
  public static final int STATIC = 29;
  public static final int LSHIFT = 68;
  public static final int XOR = 79;
  public static final int FLOATING_POINT_LITERAL = 96;
  public static final int MINUSEQ = 88;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PRINT",
  "MAIN",
  "BOOLEAN",
  "BYTE",
  "SHORT",
  "INT",
  "LONG",
  "CHAR",
  "FLOAT",
  "DOUBLE",
  "LBRACK",
  "RBRACK",
  "DOT",
  "SEMICOLON",
  "MULT",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "EQ",
  "LPAREN",
  "RPAREN",
  "COLON",
  "PACKAGE",
  "IMPORT",
  "PUBLIC",
  "PROTECTED",
  "PRIVATE",
  "STATIC",
  "ABSTRACT",
  "FINAL",
  "NATIVE",
  "SYNCHRONIZED",
  "TRANSIENT",
  "VOLATILE",
  "CLASS",
  "EXTENDS",
  "IMPLEMENTS",
  "VOID",
  "THROWS",
  "THIS",
  "SUPER",
  "INTERFACE",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "DO",
  "WHILE",
  "FOR",
  "BREAK",
  "CONTINUE",
  "RETURN",
  "THROW",
  "TRY",
  "CATCH",
  "FINALLY",
  "NEW",
  "PLUSPLUS",
  "MINUSMINUS",
  "PLUS",
  "MINUS",
  "COMP",
  "NOT",
  "DIV",
  "MOD",
  "LSHIFT",
  "RSHIFT",
  "URSHIFT",
  "LT",
  "GT",
  "LTEQ",
  "GTEQ",
  "INSTANCEOF",
  "EQEQ",
  "NOTEQ",
  "AND",
  "XOR",
  "OR",
  "ANDAND",
  "OROR",
  "QUESTION",
  "MULTEQ",
  "DIVEQ",
  "MODEQ",
  "PLUSEQ",
  "MINUSEQ",
  "LSHIFTEQ",
  "RSHIFTEQ",
  "URSHIFTEQ",
  "ANDEQ",
  "XOREQ",
  "OREQ",
  "INTEGER_LITERAL",
  "FLOATING_POINT_LITERAL",
  "BOOLEAN_LITERAL",
  "CHARACTER_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER",
  "NULL_LITERAL",
  "STRICTFP",
  "CONST",
  "GOTO"
  };
}

